- name: docker package installation
  hosts: all
  gather_facts: False
  become: True
  tasks:
    - name: install pip3
      apt:
        name: python3-pip
        state: present
    - name: Install docker
      command: pip3 install docker
